Repository wecode-bootcamp-korea/15-1st-LineAmigos-frontend, pull requests merged in 2020-12, with the labels that each got.

#2 package.json 수정
  package-lock.json
  package.json
Labels: Status: 도움 요청

#3 common.scss 수정, index.html font awesome 링크 추가, react-slick packages 추가, images 추가
  package-lock.json
  package.json
  public/data/data.json
  public/images/arrow-right-bold.png
  public/images/arrow-right.png
  public/images/line-amigos-logo-black.png
  public/images/line-amigos-logo-default.png
  public/images/line-amigos-logo-white.png
  public/images/line-amigos-logo.png
  public/images/menu.png
  public/images/naver-logo.png
  public/images/search.png
  public/images/shop-bold.png
  public/images/shop.png
  public/index.html
  src/styles/common.scss
Labels: Status: Accepted

#5 [15기 이은진] Fix: Header 컴포넌트 컨플릭트 해결 완료, 멘토님 리뷰 반영
  config.js
  package-lock.json
  package.json
  public/data/data.json
  public/data/productsInfos.json
  public/images/banner-01.jpg
  public/images/banner-02.jpg
  public/images/banner-03.jpg
  src/Components/Header/Category.jsx
  src/Components/Header/Category.scss
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
  src/Components/Nav/Nav.jsx
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.jsx
  src/Routes.js
Labels: Status: 리뷰 요청

#7 [강경오]상품 상세 페이지 레이아웃 진행중
  config.js
  package-lock.json
  package.json
  public/data/mockData.json
  public/data/reviewData.json
  src/Components/Header/Header.jsx
  src/Pages/ProductDetail/Component/CalTotal/CalTotal.jsx
  src/Pages/ProductDetail/Component/CalTotal/CalTotal.scss
  src/Pages/ProductDetail/Component/ImgPurchInfo.jsx
  src/Pages/ProductDetail/Component/ImgPurchInfo.scss
  src/Pages/ProductDetail/Component/ImgSlide/ImgSlide.jsx
  src/Pages/ProductDetail/Component/ImgSlide/ImgSlide.scss
  src/Pages/ProductDetail/Component/Product.jsx
  src/Pages/ProductDetail/Component/Product.scss
  src/Pages/ProductDetail/Component/ProductDescriptions/ProductDescriptions.jsx
  src/Pages/ProductDetail/Component/ProductDescriptions/ProductDescriptions.scss
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.jsx
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.scss
  src/Pages/ProductDetail/Component/Review/Review.jsx
  src/Pages/ProductDetail/Component/Review/Review.scss
  src/Pages/ProductDetail/Component/Review/ReviewContent/ReviewContent.jsx
  src/Pages/ProductDetail/Component/Review/ReviewContent/ReviewContent.scss
  src/Pages/ProductDetail/Component/function.js
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#11 [15기 안미현] 코드 리뷰 반영
  config.js
  package-lock.json
  package.json
  public/data/filterData.json
  public/data/productsInfos.json
  public/images/header.jpg
  public/images/lineamigos .jpg
  public/images/productList_banner.jpg
  public/images/productList_banner2.jpg
  public/images/productList_banner3.jpg
  public/images/productList_banner4.jpg
  src/Components/Footer/Footer.jsx
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/component/.Product.jsx.swp
  src/Pages/ProductList/component/.Products.jsx.swp
  src/Pages/ProductList/component/Filter.jsx
  src/Pages/ProductList/component/Filter.scss
  src/Pages/ProductList/component/Filters.jsx
  src/Pages/ProductList/component/Filters.scss
  src/Pages/ProductList/component/Pagination.jsx
  src/Pages/ProductList/component/Product.jsx
  src/Pages/ProductList/component/Product.scss
  src/Pages/ProductList/component/Products.jsx
  src/Pages/ProductList/component/SideCategory.jsx
  src/Pages/ProductList/component/SideCategory.scss
  src/Pages/ProductList/component/pagination.scss
  src/Pages/ProductList/component/products.scss
  src/Pages/SignUp/SignUp.jsx
  src/Routes.js
  src/index.js
  src/styles/reset.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#8 [15기 이은진] Refactor: Main 컴포넌트 멘토 리뷰 반영, 기능구현 완료(제발 이것 먼저 merge 해주세요)
  config.js
  package-lock.json
  public/data/categories.json
  public/data/products.json
  public/data/productsInfos.json
  public/data/reviews.json
  public/images/Main/main-slider-01.jpg
  public/images/Main/main-slider-02.jpg
  public/images/Main/main-slider-03.jpg
  public/images/Main/main-slider-04.jpg
  public/images/add-to-wishlist.png
  public/images/banner-img-01.jpg
  public/images/banner-img-02.jpg
  public/images/banner-img-03.jpg
  public/images/cart-icon.png
  public/images/click-template.webp
  public/images/product.jpg
  public/index.html
  src/Components/Header/Category.jsx
  src/Components/Header/Header.jsx
  src/Pages/Main/BannerSlider.jsx
  src/Pages/Main/BannerSlider.scss
  src/Pages/Main/ItemClickButton/ItemClickButton.jsx
  src/Pages/Main/ItemClickButton/ItemClickButton.scss
  src/Pages/Main/ItemClickPlate.jsx
  src/Pages/Main/ItemClickPlate.scss
  src/Pages/Main/Main.jsx
  src/Pages/Main/Main.scss
  src/Pages/Main/MainReviews/ReviewCard.js
  src/Pages/Main/MainReviews/ReviewCard.scss
  src/Pages/Main/MainSlider.jsx
  src/Pages/Main/MainSlider.scss
  src/Pages/Main/NewProductsSlider.jsx
  src/Pages/Main/NewProductsSlider.scss
  src/Pages/Main/ReviewSection.jsx
  src/Pages/Main/ReviewSection.scss
  src/Pages/Main/SliderCard/SliderCard.jsx
  src/Pages/Main/SliderCard/SliderCard.scss
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#13 [15기 안미현] 로그인 페이지 scss 수정
  src/Pages/Login/Login.jsx
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#10 [15기 이은진] 장바구니 프론트 기능 구현
  public/data/productsInfos.json
  public/images/nPayBtn.png
  public/index.html
  src/Pages/Cart/Cart.jsx
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/CartItem.jsx
  src/Pages/Cart/CartItem.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#14 [15기 이은진] Feature/header 컨플릭트 해결
  package-lock.json
  package.json
  src/Components/Header/Category.jsx
  src/Components/Header/Category.scss
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
Labels: Status: 리뷰 요청

#12 [15기 강경오] 상품 추천 페이지네이션 진행중
  config.js
  package-lock.json
  src/Pages/ProductDetail/Component/ImgPurchInfo.jsx
  src/Pages/ProductDetail/Component/ImgPurchInfo.scss
  src/Pages/ProductDetail/Component/ImgSlide/ImgSlide.scss
  src/Pages/ProductDetail/Component/Product.jsx
  src/Pages/ProductDetail/Component/Product.scss
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.jsx
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.scss
  src/Pages/ProductDetail/Component/Review/Review.jsx
  src/Pages/ProductDetail/Component/Review/Review.scss
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/component/Products.jsx
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#15 [15기 안미현] 상품리스트 페이지 메뉴필터기능 추가 (질문 두가지 있습니다!)
  config.js
  package-lock.json
  public/data/filterData.json
  src/.index.js.swp
  src/Pages/Login/Login.scss
  src/Pages/ProductDetail/Component/ImgPurchInfo.jsx
  src/Pages/ProductDetail/Component/ImgPurchInfo.scss
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/component/.Product.jsx.swp
  src/Pages/ProductList/component/.Products.jsx.swp
  src/Pages/ProductList/component/Filters.jsx
  src/Pages/ProductList/component/Product.jsx
  src/Pages/ProductList/component/Product.scss
  src/Pages/ProductList/component/Products.jsx
  src/Pages/ProductList/component/SideCategory.jsx
  src/Pages/ProductList/component/products.scss
  src/Pages/SignUp/.IdPwForm.jsx.swp
  src/Pages/SignUp/SignUp.jsx
  src/styles/common.scss
Labels: Status: Accepted

#16 [15기 이은진] main, header css 수정
  config.js
  package-lock.json
  public/data/mainSlider.json
  src/Components/Footer/Footer.scss
  src/Components/Header/Category.jsx
  src/Components/Header/Category.scss
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
  src/Pages/Cart/Cart.jsx
  src/Pages/Main/BannerSlider.jsx
  src/Pages/Main/BannerSlider.scss
  src/Pages/Main/ItemClickButton/ItemClickButton.jsx
  src/Pages/Main/ItemClickPlate.scss
  src/Pages/Main/Main.jsx
  src/Pages/Main/MainReviews/ReviewCard.js
  src/Pages/Main/MainReviews/ReviewCard.scss
  src/Pages/Main/MainSlider.jsx
  src/Pages/Main/MainSlider.scss
  src/Pages/Main/NewProductsSlider.scss
  src/Pages/Main/ReviewSection.jsx
  src/Pages/Main/ReviewSection.scss
  src/Pages/Main/SliderCard/SliderCard.jsx
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#17 [라인아미고스 최종 파일] 회원가입 로직 수정 및 프로젝트 완료
  src/Components/Header/Category.jsx
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
  src/Pages/Login/Login.jsx
  src/Pages/ProductDetail/Component/ImgPurchInfo.jsx
  src/Pages/ProductDetail/Component/ImgPurchInfo.scss
  src/Pages/ProductDetail/Component/Product.scss
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.jsx
  src/Pages/ProductDetail/Component/Recommadations/Recommandations.scss
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/component/Product.jsx
  src/Pages/ProductList/component/Product.scss
  src/Pages/SignUp/SignUp.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중
